name: Playwright-Python_Nuevo-Framework

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # Permite ejecutar el workflow manualmente y seleccionar el ambiente
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el ambiente de ejecuci贸n (e.g., qa, prod)'
        required: true
        default: 'qa'
        type: choice
        options:
        - dev
        - staging
        - prod
        - qa

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    #  CRTICO: Configuraci贸n de Permisos para Despliegue en Pages
    permissions:
      contents: read
      pages: write
      id-token: write # Requerido por actions/deploy-pages

    steps:
      - name: Checkout C贸digo Fuente
        uses: actions/checkout@v4


      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.9'
      
      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.9' # Aseg煤rate de que esta sea la versi贸n de Python que usas
      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Instalar navegadores de Playwright
        run: playwright install --with-deps

      - name: Crear directorio de ambiente
        run: mkdir -p environments

      - name: Crear archivo de ambiente para el CI (SIMULADO)
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
        run: |
          case ${{ env.ENVIRONMENT }} in
            dev)
              echo "${{ secrets.DEV_ENV_VARS }}" > environments/dev.env
              ;;
            staging)
              echo "${{ secrets.STAGING_ENV_VARS }}" > environments/staging.env
              ;;
            prod)
              echo "${{ secrets.PROD_ENV_VARS }}" > environments/prod.env
              ;;
            *)
              echo "${{ secrets.QA_ENV_VARS }}" > environments/qa.env
              ;;
          esac

      - name: Ejecutar pruebas de Playwright (Configuraci贸n desde pyproject.toml)
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'qa' }}
        run: |
          pytest tests/e2e/test_home.py tests/e2e/test_webinput.py tests/e2e/test_register.py tests/e2e/test_login.py
          
      - name: Subir informe de pruebas de Playwright (para debugging o descarga)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-raw-report
          path: reports/html1/playwright_reporte.html
          retention-days: 30